version: '2'
services:
  rtmp:
    image: encode/nginx-rtmp-docker
    hostname: rtmpstream.coadcorp.com
    restart: always
    container_name: rtmp-stream
    volumes:
      - ./nginx.conf:/config/nginx.conf
      - ./recordings:/recordings
      - ./hls:/hls      
      - ./wwwroot:/usr/local/www
    environment:
      PASSWORD: p@ssw0rd
    ports:
      - 80:80/tcp
      - 1935:1935